# Generated by Django 5.0.3 on 2024-04-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fraquezaPokemon',
            field=models.CharField(default='SOME STRING', max_length=150),
        ),
        migrations.AddField(
            model_name='item',
            name='tipoPokemon',
            field=models.CharField(default='SOME STRING', max_length=150),
        ),
    ]
